services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      container_nama: porto
      restart: always
      ports:
       - "3001:3001"
      environment:
       - NODE_ENV=production
       - PORT=3001
